name: Digital Media Creations
favicon: null
layout_spectrum: 0.7735356707125902
typography_spectrum: 0.9228897579014301
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0399181810207665
  lightness: 0.6605314565822482
  saturation: 0.7380629805848002
  rhythmicContrast: 0.6150834592990577
purpose: []
